# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: ja-JP
reviews:
  request_changes_workflow: true
  auto_review:
    enabled: true
    base_branches:
      - "*"
code_generation:
  docstrings:
    language: ja-JP
