name: 'Setup Frontend'
description: 'Setup Flutter environment for frontend. Installs dependencies and configures caching.'

runs:
  using: 'composite'
  steps:
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        cache: true

    - name: Flutter pub get
      working-directory: frontend
      run: flutter pub get
      shell: bash
