# yaml-language-server: $schema=https://www.schemastore.org/github-action.json
name: Terraform CI
description: Continuous integration for Terraform.
inputs:
  env:
    required: true
    description: terraformを適用する環境

  root:
    required: true
    description: terraformを適用するディレクトリ

runs:
  using: composite
  steps:
    - run: echo "env:${{ inputs.env }} root:${{ inputs.root }}
      shell: bash
      working-directory: ${{ inputs.root }}

    - run: pwd
      shell: bash
      working-directory: ${{ inputs.root }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.14.3

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true
      shell: bash
      working-directory: ${{ inputs.root }}

    - name: Terraform Init
      id: init
      run: terraform init -input=false
      shell: bash
      working-directory: ${{ inputs.root }}

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
      shell: bash
      working-directory: ${{ inputs.root }}

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color -input=false
      continue-on-error: true
      shell: bash
      working-directory: ${{ inputs.root }}

    - uses: actions/github-script@v7
      if: github.event_name == 'pull_request'
      env:
        PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
      with:
        script: |
          // 1. Retrieve existing bot comments for the PR
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          })
          const botComment = comments.find(comment => {
            return comment.user.type === 'Bot' && comment.body.includes('Terraform Format and Style - ${{ inputs.env }}')
          })

          // 2. Prepare format of the comment
          const output = `#### Terraform Format and Style - ${{ inputs.env }} 🖌\`${{ steps.fmt.outcome }}\`
          #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
          #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
          <details><summary>Validation Output</summary>

          \`\`\`\n
          ${{ steps.validate.outputs.stdout }}
          \`\`\`

          </details>

          #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

          <details><summary>Show Plan</summary>

          \`\`\`\n
          ${process.env.PLAN}
          \`\`\`

          </details>

          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;

          // 3. If we have a comment, update it, otherwise create a new one
          if (botComment) {
            github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: botComment.id,
              body: output
            })
          } else {
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
          }
