# yaml-language-server: $schema=https://www.schemastore.org/github-action.json
name: Setup Backend
description: Setup Python environment with uv for backend. Installs dependencies and configures caching.

runs:
  using: composite
  steps:
    - name: Setup uv
      uses: astral-sh/setup-uv@v7
      with:
        python-version: "3.13"
        enable-cache: true

    - name: Install dependencies
      working-directory: backend
      run: uv sync --all-groups
      shell: bash
